conditions:
  IFR:
    blink: false
    color: '#ff0000'
  INOP:
    blink: false
    color: '#000000'
  INVALID:
    blink: true
    color: '#faff00'
  LIFR:
    blink: false
    color: '#ff00ff'
  MVFR:
    blink: false
    color: '#0000ff'
  NIGHT:
    blink: false
    color: '#ffff00'
  NIGHT_DARK:
    blink: false
    color: '#141400'
  SMOKE:
    blink: false
    color: '#323232'
  VFR:
    blink: false
    color: '#00ff00'
metar_inop_age: 180
metar_invalid_age: 90
metar_refresh_interval: 15
night_lights: true
pixel_count: 2
pixel_map:
  '0': KRDU
  '1': KLHZ
pixelcount: 2
renderer_config:
  hostname: 127.0.0.1
  name: dummy
  port: 5006
setup_complete: true
sunrise_refresh_interval: 1080
#The following shows what will be displayed on the map by default (int)
#Possible values: 
# 1 - Metar (default) 
# 2 - Places I've Been (requires FF Logbook configuration)
# 3 - Places I've been Heatmap (requires FF logbook configuration) (todo)
# 4 - Density Altitude Heatmap (todo)
display: 2
#ForeFlight Configuration Parameters
ff_username: 'email'
ff_password: 'pass'
# Refresh Interval in hours (default 24 hrs)
ff_refresh_interval: 24